language: node_js
node_js: 8
sudo: required
services:
  - docker
before_install:
  - docker pull kennethreitz/httpbin
  - docker run -d -p 80:80 kennethreitz/httpbin
  - docker ps -a
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script:
  - npm test
