language: node_js
node_js: 8
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - xvfb
before_install:
  - docker pull kennethreitz/httpbin
  - docker run -d -p 80:80 kennethreitz/httpbin
  - docker ps -a
before_script:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script:
  - npm test
